# 08 — Chunk size and retrieval limits

A 3,072-dimensional embedding is a vector shape, not a character limit. This experiment holds the source and questions constant while varying the maximum chunk length. It reports full BM25, Gemini cosine, and RRF rankings.

In [1]:
import os
from pathlib import Path
import sys

root_hint = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
sys.path.insert(0, str(root_hint / 'notebooks'))
from helpers import bootstrap, display_table
ROOT = bootstrap()
from app.domain.models import Chunk, SearchQuery, SourceLocator
from app.retrieval.dense import GeminiDenseIndex
from app.retrieval.hybrid import HybridRetriever
from ingestion.chunking import chunk_pages
from ingestion.exporters import read_result
from ingestion.indexing import build_runtime_embedding_cache

RUN_GEMINI = os.getenv('RUN_GEMINI_CHUNK_EXPERIMENT', '0') == '1'
SOURCE = ROOT / 'data' / 'processed' / 'foyer_group_qrt_2025'
source_result = read_result(SOURCE)
{'run_gemini': RUN_GEMINI, 'source_pages': len(source_result.pages)}

{'run_gemini': False, 'source_pages': 10}

In [2]:
sizes = (900, 1800, 3000, 4800)
variants = {}
for size in sizes:
    artifacts = chunk_pages(
        source_result.manifest.document_id,
        source_result.manifest.title,
        source_result.pages,
        source_result.manifest.entity,
        source_result.manifest.period,
        max_characters=size,
    )
    variants[size] = [
        Chunk(
            id=artifact.id,
            document_id=artifact.document_id,
            chunk_type=f'experimental_page_text_{size}',
            text=artifact.contextualized_text,
            locator=SourceLocator(
                document_id=artifact.document_id,
                document_title=source_result.manifest.title,
                version=source_result.manifest.sha256[:12],
                source_url=source_result.manifest.source_url,
                page=artifact.page_start,
                section_path=artifact.section_path,
            ),
        )
        for artifact in artifacts
    ]
summary_rows = [
    {
        'max_characters': size,
        'chunks': len(chunks),
        'minimum_characters': min(map(lambda item: len(item.text), chunks)),
        'average_characters': round(sum(map(lambda item: len(item.text), chunks)) / len(chunks), 1),
        'maximum_characters_with_context': max(map(lambda item: len(item.text), chunks)),
    }
    for size, chunks in variants.items()
]
display_table(summary_rows)

,max_characters,chunks,minimum_characters,average_characters,maximum_characters_with_context
0,900,113,94,672.2,987
1,1800,73,103,1052.8,1887
2,3000,56,93,1365.4,3087
3,4800,50,103,1545.8,4887

In [3]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
variant_rows = [
    {
        'max_characters': size,
        'chunk_id': chunk.id,
        'page': chunk.locator.page,
        'characters': len(chunk.text),
        'full_text': chunk.text,
    }
    for size, chunks in variants.items()
    for chunk in chunks
]
display_table(variant_rows)

     max_characters                               chunk_id  page  characters  \
0               900  foyer_group_qrt_2025-p001-text-000-00     1         115
1               900  foyer_group_qrt_2025-p001-text-001-00     1         103
2               900  foyer_group_qrt_2025-p001-text-002-00     1         987
3               900  foyer_group_qrt_2025-p001-text-002-01     1         984
4               900  foyer_group_qrt_2025-p001-text-002-02     1         978
5               900  foyer_group_qrt_2025-p001-text-002-03     1         983
6               900  foyer_group_qrt_2025-p001-text-002-04     1         916
7               900  foyer_group_qrt_2025-p001-text-002-05     1         964
8               900  foyer_group_qrt_2025-p001-text-002-06     1         239
9               900  foyer_group_qrt_2025-p002-text-000-00     2         115
10              900  foyer_group_qrt_2025-p002-text-001-00     2         103
11              900  foyer_group_qrt_2025-p002-text-002-00     2         982
12              900  foyer_group_qrt_2025-p002-text-002-01     2         979
13              900  foyer_group_qrt_2025-p002-text-002-02     2         987
14              900  foyer_group_qrt_2025-p002-text-002-03     2         982
15              900  foyer_group_qrt_2025-p002-text-002-04     2         916
16              900  foyer_group_qrt_2025-p002-text-002-05     2         799
17              900  foyer_group_qrt_2025-p003-text-000-00     3         115
18              900  foyer_group_qrt_2025-p003-text-001-00     3         153
19              900  foyer_group_qrt_2025-p003-text-002-00     3         333
20              900  foyer_group_qrt_2025-p003-text-003-00     3         947
21              900  foyer_group_qrt_2025-p003-text-003-01     3         895
22              900  foyer_group_qrt_2025-p003-text-003-02     3         467
23              900  foyer_group_qrt_2025-p003-text-003-03     3         898
24              900  foyer_group_qrt_2025-p003-text-003-04     3         883
25              900  foyer_group_qrt_2025-p003-text-003-05     3         788
26              900  foyer_group_qrt_2025-p003-text-003-06     3         864
27              900  foyer_group_qrt_2025-p003-text-003-07     3         701
28              900  foyer_group_qrt_2025-p003-text-003-08     3         748
29              900  foyer_group_qrt_2025-p003-text-004-00     3         977
30              900  foyer_group_qrt_2025-p003-text-004-01     3         900
31              900  foyer_group_qrt_2025-p003-text-004-02     3         970
32              900  foyer_group_qrt_2025-p003-text-004-03     3         917
33              900  foyer_group_qrt_2025-p003-text-004-04     3         963
34              900  foyer_group_qrt_2025-p003-text-004-05     3         926
35              900  foyer_group_qrt_2025-p003-text-004-06     3         740
36              900  foyer_group_qrt_2025-p003-text-004-07     3          94
37              900  foyer_group_qrt_2025-p004-text-000-00     4         115
38              900  foyer_group_qrt_2025-p004-text-001-00     4         153
39              900  foyer_group_qrt_2025-p004-text-002-00     4         891
40              900  foyer_group_qrt_2025-p004-text-002-01     4         942
41              900  foyer_group_qrt_2025-p004-text-002-02     4         806
42              900  foyer_group_qrt_2025-p004-text-002-03     4         903
43              900  foyer_group_qrt_2025-p004-text-002-04     4         952
44              900  foyer_group_qrt_2025-p004-text-002-05     4         981
45              900  foyer_group_qrt_2025-p004-text-002-06     4         599
46              900  foyer_group_qrt_2025-p005-text-000-00     5         115
47              900  foyer_group_qrt_2025-p005-text-001-00     5         182
48              900  foyer_group_qrt_2025-p005-text-002-00     5         946
49              900  foyer_group_qrt_2025-p005-text-002-01     5         899
50              900  foyer_group_qrt_2025-p005-text-002-02     5         424
51              900  foyer_group_qrt_2025-p006-text-000-00     6         115
52              900  foyer_group_qrt_2025-p006-text-001-00     6         116
53              900  foyer_group_qrt_2025-p006-text-002-00     6         986
54              900  foyer_group_qrt_2025-p006-text-002-01     6         911
55              900  foyer_group_qrt_2025-p006-text-002-02     6         938
56              900  foyer_group_qrt_2025-p006-text-002-03     6         891
57              900  foyer_group_qrt_2025-p006-text-002-04     6         983
58              900  foyer_group_qrt_2025-p006-text-002-05     6         761
59              900  foyer_group_qrt_2025-p006-text-003-00     6         286
60              900  foyer_group_qrt_2025-p006-text-004-00     6         987
61              900  foyer_group_qrt_2025-p006-text-004-01     6         903
62              900  foyer_group_qrt_2025-p006-text-004-02     6         982
63              900  foyer_group_qrt_2025-p006-text-004-03     6         975
64              900  foyer_group_qrt_2025-p006-text-004-04     6         525
65              900  foyer_group_qrt_2025-p007-text-000-00     7         115
66              900  foyer_group_qrt_2025-p007-text-001-00     7         116
67              900  foyer_group_qrt_2025-p007-text-002-00     7         987
68              900  foyer_group_qrt_2025-p007-text-002-01     7         987
69              900  foyer_group_qrt_2025-p007-text-002-02     7         986
70              900  foyer_group_qrt_2025-p007-text-002-03     7         987
71              900  foyer_group_qrt_2025-p007-text-002-04     7         987
72              900  foyer_group_qrt_2025-p007-text-002-05     7         217
73              900  foyer_group_qrt_2025-p008-text-000-00     8         115
74              900  foyer_group_qrt_2025-p008-text-001-00     8         116
75              900  foyer_group_qrt_2025-p008-text-002-00     8         987
76              900  foyer_group_qrt_2025-p008-text-002-01     8         944
77              900  foyer_group_qrt_2025-p009-text-000-00     9         115
78              900  foyer_group_qrt_2025-p009-text-001-00     9         180
79              900  foyer_group_qrt_2025-p009-text-002-00     9         987
80              900  foyer_group_qrt_2025-p009-text-002-01     9         712
81              900  foyer_group_qrt_2025-p009-text-003-00     9         603
82              900  foyer_group_qrt_2025-p009-text-004-00     9         229
83              900  foyer_group_qrt_2025-p009-text-005-00     9         981
84              900  foyer_group_qrt_2025-p009-text-005-01     9         497
85              900  foyer_group_qrt_2025-p009-text-006-00     9         206
86              900  foyer_group_qrt_2025-p009-text-007-00     9         926
87              900  foyer_group_qrt_2025-p009-text-007-01     9         953
88              900  foyer_group_qrt_2025-p009-text-007-02     9         355
89              900  foyer_group_qrt_2025-p010-text-000-00    10         115
90              900  foyer_group_qrt_2025-p010-text-001-00    10         137
91              900  foyer_group_qrt_2025-p010-text-002-00    10         220
92              900  foyer_group_qrt_2025-p010-text-003-00    10         984
93              900  foyer_group_qrt_2025-p010-text-003-01    10         542
94              900  foyer_group_qrt_2025-p010-text-003-02    10         727
95              900  foyer_group_qrt_2025-p010-text-003-03    10         253
96              900  foyer_group_qrt_2025-p010-text-003-04    10         842
97              900  foyer_group_qrt_2025-p010-text-003-05    10         902
98              900  foyer_group_qrt_2025-p010-text-003-06    10         734
99              900  foyer_group_qrt_2025-p010-text-003-07    10         423
100             900  foyer_group_qrt_2025-p010-text-003-08    10         789
101             900  foyer_group_qrt_2025-p010-text-003-09    10         757
102             900  foyer_group_qrt_2025-p010-text-003-10    10         431
103             900  foyer_group_qrt_2025-p010-text-003-11    10         671
104             900  foyer_group_qrt_2025-p010-text-003-12    10         721
105             900  foyer_group_qrt_2025-p010-text-003-13    10         384
106             900  foyer_group_qrt_2025-p010-text-004-00    10         977
107             900  foyer_group_qrt_2025-p010-text-004-01    10         981
108             900  foyer_group_qrt_2025-p010-text-004-02    10         984
109             900  foyer_group_qrt_2025-p010-text-004-03    10         941
110             900  foyer_group_qrt_2025-p010-text-004-04    10         982
111             900  foyer_group_qrt_2025-p010-text-004-05    10         927
112             900  foyer_group_qrt_2025-p010-text-004-06    10         568
113            1800  foyer_group_qrt_2025-p001-text-000-00     1         115
114            1800  foyer_group_qrt_2025-p001-text-001-00     1         103
115            1800  foyer_group_qrt_2025-p001-text-002-00     1        1884
116            1800  foyer_group_qrt_2025-p001-text-002-01     1        1878
117            1800  foyer_group_qrt_2025-p001-text-002-02     1        1866
118            1800  foyer_group_qrt_2025-p001-text-002-03     1         239
119            1800  foyer_group_qrt_2025-p002-text-000-00     2         115
120            1800  foyer_group_qrt_2025-p002-text-001-00     2         103
121            1800  foyer_group_qrt_2025-p002-text-002-00     2        1887
122            1800  foyer_group_qrt_2025-p002-text-002-01     2        1882
123            1800  foyer_group_qrt_2025-p002-text-002-02     2        1628
124            1800  foyer_group_qrt_2025-p003-text-000-00     3         115
125            1800  foyer_group_qrt_2025-p003-text-001-00     3         153
126            1800  foyer_group_qrt_2025-p003-text-002-00     3         333
127            1800  foyer_group_qrt_2025-p003-text-003-00     3        1881
128            1800  foyer_group_qrt_2025-p003-text-003-01     3        1450
129            1800  foyer_group_qrt_2025-p003-text-003-02     3        1708
130            1800  foyer_group_qrt_2025-p003-text-003-03     3        1588
131            1800  foyer_group_qrt_2025-p003-text-003-04     3         748
132            1800  foyer_group_qrt_2025-p003-text-004-00     3        1872
133            1800  foyer_group_qrt_2025-p003-text-004-01     3        1879
134            1800  foyer_group_qrt_2025-p003-text-004-02     3        1884
135            1800  foyer_group_qrt_2025-p003-text-004-03     3        1029
136            1800  foyer_group_qrt_2025-p004-text-000-00     4         115
137            1800  foyer_group_qrt_2025-p004-text-001-00     4         153
138            1800  foyer_group_qrt_2025-p004-text-002-00     4        1887
139            1800  foyer_group_qrt_2025-p004-text-002-01     4        1792
140            1800  foyer_group_qrt_2025-p004-text-002-02     4        1887
141            1800  foyer_group_qrt_2025-p004-text-002-03     4         599
142            1800  foyer_group_qrt_2025-p005-text-000-00     5         115
143            1800  foyer_group_qrt_2025-p005-text-001-00     5         182
144            1800  foyer_group_qrt_2025-p005-text-002-00     5        1886
145            1800  foyer_group_qrt_2025-p005-text-002-01     5         424
146            1800  foyer_group_qrt_2025-p006-text-000-00     6         115
147            1800  foyer_group_qrt_2025-p006-text-001-00     6         116
148            1800  foyer_group_qrt_2025-p006-text-002-00     6        1811
149            1800  foyer_group_qrt_2025-p006-text-002-01     6        1838
150            1800  foyer_group_qrt_2025-p006-text-002-02     6        1657
151            1800  foyer_group_qrt_2025-p006-text-003-00     6         286
152            1800  foyer_group_qrt_2025-p006-text-004-00     6        1803
153            1800  foyer_group_qrt_2025-p006-text-004-01     6        1870
154            1800  foyer_group_qrt_2025-p006-text-004-02     6         525
155            1800  foyer_group_qrt_2025-p007-text-000-00     7         115
156            1800  foyer_group_qrt_2025-p007-text-001-00     7         116
157            1800  foyer_group_qrt_2025-p007-text-002-00     7        1887
158            1800  foyer_group_qrt_2025-p007-text-002-01     7        1887
159            1800  foyer_group_qrt_2025-p007-text-002-02     7        1117
160            1800  foyer_group_qrt_2025-p008-text-000-00     8         115
161            1800  foyer_group_qrt_2025-p008-text-001-00     8         116
162            1800  foyer_group_qrt_2025-p008-text-002-00     8        1844
163            1800  foyer_group_qrt_2025-p009-text-000-00     9         115
164            1800  foyer_group_qrt_2025-p009-text-001-00     9         180
165            1800  foyer_group_qrt_2025-p009-text-002-00     9        1612
166            1800  foyer_group_qrt_2025-p009-text-003-00     9         603
167            1800  foyer_group_qrt_2025-p009-text-004-00     9         229
168            1800  foyer_group_qrt_2025-p009-text-005-00     9        1466
169            1800  foyer_group_qrt_2025-p009-text-006-00     9         206
170            1800  foyer_group_qrt_2025-p009-text-007-00     9        1887
171            1800  foyer_group_qrt_2025-p009-text-007-01     9         355
172            1800  foyer_group_qrt_2025-p010-text-000-00    10         115
173            1800  foyer_group_qrt_2025-p010-text-001-00    10         137
174            1800  foyer_group_qrt_2025-p010-text-002-00    10         220
175            1800  foyer_group_qrt_2025-p010-text-003-00    10        1881
176            1800  foyer_group_qrt_2025-p010-text-003-01    10        1310
177            1800  foyer_group_qrt_2025-p010-text-003-02    10        1846
178            1800  foyer_group_qrt_2025-p010-text-003-03    10        1400
179            1800  foyer_group_qrt_2025-p010-text-003-04    10        1747
180            1800  foyer_group_qrt_2025-p010-text-003-05    10        1367
181            1800  foyer_group_qrt_2025-p010-text-003-06    10        1417
182            1800  foyer_group_qrt_2025-p010-text-004-00    10        1886
183            1800  foyer_group_qrt_2025-p010-text-004-01    10        1884
184            1800  foyer_group_qrt_2025-p010-text-004-02    10        1823
185            1800  foyer_group_qrt_2025-p010-text-004-03    10         568
186            3000  foyer_group_qrt_2025-p001-text-000-00     1         115
187            3000  foyer_group_qrt_2025-p001-text-001-00     1         103
188            3000  foyer_group_qrt_2025-p001-text-002-00     1        3077
189            3000  foyer_group_qrt_2025-p001-text-002-01     1        2602
190            3000  foyer_group_qrt_2025-p002-text-000-00     2         115
191            3000  foyer_group_qrt_2025-p002-text-001-00     2         103
192            3000  foyer_group_qrt_2025-p002-text-002-00     2        3034
193            3000  foyer_group_qrt_2025-p002-text-002-01     2        2272
194            3000  foyer_group_qrt_2025-p003-text-000-00     3         115
195            3000  foyer_group_qrt_2025-p003-text-001-00     3         153
196            3000  foyer_group_qrt_2025-p003-text-002-00     3         333
197            3000  foyer_group_qrt_2025-p003-text-003-00     3        3002
198            3000  foyer_group_qrt_2025-p003-text-003-01     3        2844
199            3000  foyer_group_qrt_2025-p003-text-003-02     3        1973
200            3000  foyer_group_qrt_2025-p003-text-004-00     3        2930
201            3000  foyer_group_qrt_2025-p003-text-004-01     3        3037
202            3000  foyer_group_qrt_2025-p003-text-004-02     3         429
203            3000  foyer_group_qrt_2025-p004-text-000-00     4         115
204            3000  foyer_group_qrt_2025-p004-text-001-00     4         153
205            3000  foyer_group_qrt_2025-p004-text-002-00     4        3078
206            3000  foyer_group_qrt_2025-p004-text-002-01     4        2996
207            3000  foyer_group_qrt_2025-p005-text-000-00     5         115
208            3000  foyer_group_qrt_2025-p005-text-001-00     5         182
209            3000  foyer_group_qrt_2025-p005-text-002-00     5        2224
210            3000  foyer_group_qrt_2025-p006-text-000-00     6         115
211            3000  foyer_group_qrt_2025-p006-text-001-00     6         116
212            3000  foyer_group_qrt_2025-p006-text-002-00     6        3078
213            3000  foyer_group_qrt_2025-p006-text-002-01     6        2251
214            3000  foyer_group_qrt_2025-p006-text-003-00     6         286
215            3000  foyer_group_qrt_2025-p006-text-004-00     6        3076
216            3000  foyer_group_qrt_2025-p006-text-004-01     6        1124
217            3000  foyer_group_qrt_2025-p007-text-000-00     7         115
218            3000  foyer_group_qrt_2025-p007-text-001-00     7         116
219            3000  foyer_group_qrt_2025-p007-text-002-00     7        3087
220            3000  foyer_group_qrt_2025-p007-text-002-01     7        1717
221            3000  foyer_group_qrt_2025-p008-text-000-00     8         115
222            3000  foyer_group_qrt_2025-p008-text-001-00     8         116
223            3000  foyer_group_qrt_2025-p008-text-002-00     8        1844
224            3000  foyer_group_qrt_2025-p009-text-000-00     9         115
225            3000  foyer_group_qrt_2025-p009-text-001-00     9         180
226            3000  foyer_group_qrt_2025-p009-text-002-00     9        1612
227            3000  foyer_group_qrt_2025-p009-text-003-00     9         603
228            3000  foyer_group_qrt_2025-p009-text-004-00     9         229
229            3000  foyer_group_qrt_2025-p009-text-005-00     9        1466
230            3000  foyer_group_qrt_2025-p009-text-006-00     9         206
231            3000  foyer_group_qrt_2025-p009-text-007-00     9        2155
232            3000  foyer_group_qrt_2025-p010-text-000-00    10         115
233            3000  foyer_group_qrt_2025-p010-text-001-00    10         137
234            3000  foyer_group_qrt_2025-p010-text-002-00    10         220
235            3000  foyer_group_qrt_2025-p010-text-003-00    10        2745
236            3000  foyer_group_qrt_2025-p010-text-003-01    10        2822
237            3000  foyer_group_qrt_2025-p010-text-003-02    10        2678
238            3000  foyer_group_qrt_2025-p010-text-003-03    10        2760
239            3000  foyer_group_qrt_2025-p010-text-003-04    10          93
240            3000  foyer_group_qrt_2025-p010-text-004-00    10        3087
241            3000  foyer_group_qrt_2025-p010-text-004-01    10        2982
242            4800  foyer_group_qrt_2025-p001-text-000-00     1         115
243            4800  foyer_group_qrt_2025-p001-text-001-00     1         103
244            4800  foyer_group_qrt_2025-p001-text-002-00     1        4887
245            4800  foyer_group_qrt_2025-p001-text-002-01     1         870
246            4800  foyer_group_qrt_2025-p002-text-000-00     2         115
247            4800  foyer_group_qrt_2025-p002-text-001-00     2         103
248            4800  foyer_group_qrt_2025-p002-text-002-00     2        4876
249            4800  foyer_group_qrt_2025-p002-text-002-01     2         463
250            4800  foyer_group_qrt_2025-p003-text-000-00     3         115
251            4800  foyer_group_qrt_2025-p003-text-001-00     3         153
252            4800  foyer_group_qrt_2025-p003-text-002-00     3         333
253            4800  foyer_group_qrt_2025-p003-text-003-00     3        4817
254            4800  foyer_group_qrt_2025-p003-text-003-01     3        3171
255            4800  foyer_group_qrt_2025-p003-text-004-00     3        4728
256            4800  foyer_group_qrt_2025-p003-text-004-01     3        1581
257            4800  foyer_group_qrt_2025-p004-text-000-00     4         115

In [4]:
test_queries = [
    ('natural', "What public evidence describes Groupe Foyer's prudential coverage in 2025?"),
    ('regulatory_labels', 'Eligible own funds, group SCR and SCR coverage ratio'),
    ('row_codes', 'S.23.01.22 R0660 R0680 R0690 C0010'),
    ('underspecified', 'Foyer solvency'),
]
ranking_rows = []
for size, chunks in variants.items():
    index_directory = ROOT / 'data' / 'processed' / 'chunk_size_experiment' / str(size)
    if RUN_GEMINI:
        build_runtime_embedding_cache(chunks, index_directory)
    if not (index_directory / 'embedding_manifest.json').exists():
        continue
    dense_index = GeminiDenseIndex(chunks, index_directory)
    retriever = HybridRetriever(chunks, dense_index=dense_index)
    for case_id, text in test_queries:
        query = SearchQuery(
            field_id='diagnostic', field_label='Diagnostic', text=text,
            document_ids=[source_result.manifest.document_id],
        )
        for final_rank, candidate in enumerate(
            retriever.search(query, k=len(chunks)), start=1
        ):
            ranking_rows.append({
                'max_characters': size,
                'case': case_id,
                'query': text,
                'final_rank': final_rank,
                'chunk_id': candidate.chunk.id,
                'page': candidate.chunk.locator.page,
                'bm25_rank': candidate.score.lexical_rank,
                'bm25_score': candidate.score.lexical_score,
                'gemini_dense_rank': candidate.score.dense_rank,
                'gemini_cosine_score': candidate.score.dense_score,
                'rrf_score': candidate.score.rrf_score,
                'contains_target_codes': any(code in candidate.chunk.text for code in ('R0660', 'R0680', 'R0690')),
                'full_text': candidate.chunk.text,
            })
if RUN_GEMINI:
    assert ranking_rows
display_table(ranking_rows)

      max_characters               case  \
0                900            natural
1                900            natural
2                900            natural
3                900            natural
4                900            natural
5                900            natural
6                900            natural
7                900            natural
8                900            natural
9                900            natural
10               900            natural
11               900            natural
12               900            natural
13               900            natural
14               900            natural
15               900            natural
16               900            natural
17               900            natural
18               900            natural
19               900            natural
20               900            natural
21               900            natural
22               900            natural
23               900            natural
24               900            natural
25               900            natural
26               900            natural
27               900            natural
28               900            natural
29               900            natural
30               900            natural
31               900            natural
32               900            natural
33               900            natural
34               900            natural
35               900            natural
36               900            natural
37               900            natural
38               900            natural
39               900            natural
40               900            natural
41               900            natural
42               900            natural
43               900            natural
44               900            natural
45               900            natural
46               900            natural
47               900            natural
48               900            natural
49               900            natural
50               900            natural
51               900            natural
52               900            natural
53               900            natural
54               900            natural
55               900            natural
56               900            natural
57               900            natural
58               900            natural
59               900            natural
60               900            natural
61               900            natural
62               900            natural
63               900            natural
64               900            natural
65               900            natural
66               900            natural
67               900            natural
68               900            natural
69               900            natural
70               900            natural
71               900            natural
72               900            natural
73               900            natural
74               900            natural
75               900            natural
76               900            natural
77               900            natural
78               900            natural
79               900            natural
80               900            natural
81               900            natural
82               900            natural
83               900            natural
84               900            natural
85               900            natural
86               900            natural
87               900            natural
88               900            natural
89               900            natural
90               900            natural
91               900            natural
92               900            natural
93               900            natural
94               900            natural
95               900            natural
96               900            natural
97               900            natural
98               900            natural
99               900            natural
100              900            natural
101              900            natural
102              900            natural
103              900            natural
104              900            natural
105              900            natural
106              900            natural
107              900            natural
108              900            natural
109              900            natural
110              900            natural
111              900            natural
112              900            natural
113              900  regulatory_labels
114              900  regulatory_labels
115              900  regulatory_labels
116              900  regulatory_labels
117              900  regulatory_labels
118              900  regulatory_labels
119              900  regulatory_labels
120              900  regulatory_labels
121              900  regulatory_labels
122              900  regulatory_labels
123              900  regulatory_labels
124              900  regulatory_labels
125              900  regulatory_labels
126              900  regulatory_labels
127              900  regulatory_labels
128              900  regulatory_labels
129              900  regulatory_labels
130              900  regulatory_labels
131              900  regulatory_labels
132              900  regulatory_labels
133              900  regulatory_labels
134              900  regulatory_labels
135              900  regulatory_labels
136              900  regulatory_labels
137              900  regulatory_labels
138              900  regulatory_labels
139              900  regulatory_labels
140              900  regulatory_labels
141              900  regulatory_labels
142              900  regulatory_labels
143              900  regulatory_labels
144              900  regulatory_labels
145              900  regulatory_labels
146              900  regulatory_labels
147              900  regulatory_labels
148              900  regulatory_labels
149              900  regulatory_labels
150              900  regulatory_labels
151              900  regulatory_labels
152              900  regulatory_labels
153              900  regulatory_labels
154              900  regulatory_labels
155              900  regulatory_labels
156              900  regulatory_labels
157              900  regulatory_labels
158              900  regulatory_labels
159              900  regulatory_labels
160              900  regulatory_labels
161              900  regulatory_labels
162              900  regulatory_labels
163              900  regulatory_labels
164              900  regulatory_labels
165              900  regulatory_labels
166              900  regulatory_labels
167              900  regulatory_labels
168              900  regulatory_labels
169              900  regulatory_labels
170              900  regulatory_labels
171              900  regulatory_labels
172              900  regulatory_labels
173              900  regulatory_labels
174              900  regulatory_labels
175              900  regulatory_labels
176              900  regulatory_labels
177              900  regulatory_labels
178              900  regulatory_labels
179              900  regulatory_labels
180              900  regulatory_labels
181              900  regulatory_labels
182              900  regulatory_labels
183              900  regulatory_labels
184              900  regulatory_labels
185              900  regulatory_labels
186              900  regulatory_labels
187              900  regulatory_labels
188              900  regulatory_labels
189              900  regulatory_labels
190              900  regulatory_labels
191              900  regulatory_labels
192              900  regulatory_labels
193              900  regulatory_labels
194              900  regulatory_labels
195              900  regulatory_labels
196              900  regulatory_labels
197              900  regulatory_labels
198              900  regulatory_labels
199              900  regulatory_labels
200              900  regulatory_labels
201              900  regulatory_labels
202              900  regulatory_labels
203              900  regulatory_labels
204              900  regulatory_labels
205              900  regulatory_labels
206              900  regulatory_labels
207              900  regulatory_labels
208              900  regulatory_labels
209              900  regulatory_labels
210              900  regulatory_labels
211              900  regulatory_labels
212              900  regulatory_labels
213              900  regulatory_labels
214              900  regulatory_labels
215              900  regulatory_labels
216              900  regulatory_labels
217              900  regulatory_labels
218              900  regulatory_labels
219              900  regulatory_labels
220              900  regulatory_labels
221              900  regulatory_labels
222              900  regulatory_labels
223              900  regulatory_labels
224              900  regulatory_labels
225              900  regulatory_labels
226              900          row_codes
227              900          row_codes
228              900          row_codes
229              900          row_codes
230              900          row_codes
231              900          row_codes
232              900          row_codes
233              900          row_codes
234              900          row_codes
235              900          row_codes
236              900          row_codes
237              900          row_codes
238              900          row_codes
239              900          row_codes
240              900          row_codes
241              900          row_codes
242              900          row_codes
243              900          row_codes
244              900          row_codes
245              900          row_codes
246              900          row_codes
247              900          row_codes
248              900          row_codes
249              900          row_codes
250              900          row_codes
251              900          row_codes
252              900          row_codes
253              900          row_codes
254              900          row_codes
255              900          row_codes
256              900          row_codes
257              900          row_codes
258              900          row_codes
259              900          row_codes
260              900          row_codes
261              900          row_codes
262              900          row_codes
263              900          row_codes
264              900          row_codes
265              900          row_codes
266              900          row_codes
267              900          row_codes
268              900          row_codes
269              900          row_codes
270              900          row_codes
271              900          row_codes
272              900          row_codes
273              900          row_codes
274              900          row_codes
275              900          row_codes
276              900          row_codes
277              900          row_codes
278              900          row_codes
279              900          row_codes
280              900          row_codes
281              900          row_codes
282              900          row_codes
283              900          row_codes
284              900          row_codes
285              900          row_codes
286              900          row_codes
287              900          row_codes
288              900          row_codes
289              900          row_codes
290              900          row_codes
291              900          row_codes
292              900          row_codes
293              900          row_codes
294              900          row_codes
295              900          row_codes
296              900          row_codes
297              900          row_codes
298              900          row_codes
299              900          row_codes
300              900          row_codes
301              900          row_codes
302              900          row_codes
303              900          row_codes
304              900          row_codes
305              900          row_codes
306              900          row_codes
307              900          row_codes
308              900          row_codes
309              900          row_codes
310              900          row_codes
311              900          row_codes
312              900          row_codes
313              900          row_codes
314              900          row_codes
315              900          row_codes
316              900          row_codes
317              900          row_codes
318              900          row_codes
319              900          row_codes
320              900          row_codes
321              900          row_codes
322              900          row_codes
323              900          row_codes
324              900          row_codes
325              900          row_codes
326              900          row_codes
327              900          row_codes
328              900          row_codes
329              900          row_codes
330              900          row_codes
331              900          row_codes
332              900          row_codes
333              900          row_codes
334              900          row_codes
335              900          row_codes
336              900          row_codes
337              900          row_codes
338              900          row_codes
339              900     underspecified
340              900     underspecified
341              900     underspecified
342              900     underspecified
343              900     underspecified
344              900     underspecified
345              900     underspecified
346              900     underspecified
347              900     underspecified
348              900     underspecified
349              900     underspecified
350              900     underspecified
351              900     underspecified
352              900     underspecified
353              900     underspecified
354              900     underspecified
355              900     underspecified
356              900     underspecified
357              900     underspecified
358              900     underspecified
359              900     underspecified
360              900     underspecified
361              900     underspecified
362              900     underspecified
363              900     underspecified
364              900     underspecified
365              900     underspecified
366              900     underspecified
367              900     underspecified
368              900     underspecified
369              900     underspecified
370              900     underspecified
371              900     underspecified
372              900     underspecified
373              900     underspecified
374              900     underspecified
375              900     underspecified
376              900     underspecified
377              900     underspecified
378              900     underspecified
379              900     underspecified
380              900     underspecified
381              900     underspecified
382              900     underspecified
383              900     underspecified
384              900     underspecified
385              900     underspecified
386              900     underspecified
387              900     underspecified
388              900     underspecified
389              900     underspecified
390              900     underspecified
391              900     underspecified
392              900     underspecified
393              900     underspecified
394              900     underspecified
395              900     underspecified
396              900     underspecified
397              900     underspecified
398              900     underspecified
399              900     underspecified
400              900     underspecified
401              900     underspecified
402              900     underspecified
403              900     underspecified
404              900     underspecified
405              900     underspecified
406              900     underspecified
407              900     underspecified
408              900     underspecified
409              900     underspecified
410              900     underspecified
411              900     underspecified
412              900     underspecified
413              900     underspecified
414              900     underspecified
415              900     underspecified
416              900     underspecified
417              900     underspecified
418              900     underspecified
419              900     underspecified
420              900     underspecified
421              900     underspecified
422              900     underspecified
423              900     underspecified
424              900     underspecified
425              900     underspecified
426              900     underspecified
427              900     underspecified
428              900     underspecified
429              900     underspecified
430              900     underspecified
431              900     underspecified
432              900     underspecified
433              900     underspecified
434              900     underspecified
435              900     underspecified
436              900     underspecified
437              900     underspecified
438              900     underspecified
439              900     underspecified
440              900     underspecified
441              900     underspecified
442              900     underspecified
443              900     underspecified
444              900     underspecified
445              900     underspecified
446              900     underspecified
447              900     underspecified
448              900     underspecified
449              900     underspecified
450              900     underspecified
451              900     underspecified
452             1800            natural
453             1800            natural
454             1800            natural
455             1800            natural
456             1800            natural
457             1800            natural
458             1800            natural
459             1800            natural
460             1800            natural
461             1800            natural
462             1800            natural
463             1800            natural
464             1800            natural
465             1800            natural
466             1800            natural
467             1800            natural
468             1800            natural
469             1800            natural
470             1800            natural
471             1800            natural
472             1800            natural
473             1800            natural
474             1800            natural
475             1800            natural
476             1800            natural
477             1800            natural
478             1800            natural
479             1800            natural
480             1800            natural
481             1800            natural
482             1800            natural
483             1800            natural
484             1800            natural
485             1800            natural
486             1800            natural
487             1800            natural
488             1800            natural
489             1800            natural
490             1800            natural
491             1800            natural
492             1800            natural
493             1800            natural
494             1800            natural
495             1800            natural
496             1800            natural
497             1800            natural

## Interpretation guardrails

Larger chunks may preserve wide tables or complete arguments, but can dilute the signal, increase embedding and generation costs, and return oversized citations. Smaller chunks improve locality but can separate labels from values. The selected size must therefore be justified by target-evidence rank and citation usability, not by embedding dimensionality.